### PR TITLE
#27 Add support for GitHub authentication

### PR DESCRIPTION
**Pull request by clvadym**
- Added button and oauth sync logic for login with GitHub.com

### CODE REVIEW

**Comment by pditommaso** [comment]
Not sure how to have this working with the [micronaut oauth](https://micronaut-projects.github.io/micronaut-security/latest/guide/index.html#oauth) (see the integration diagram). 

Currently what's happening is that when the user clicks in auth link, the token is validated by the backend. See here 

https://github.com/seqeralabs/nf-tower/blob/fc287becfae3254aaf9e985187e13d7aa622b2bd/tower-web/src/app/modules/main/component/auth/auth.component.ts#L42-L50

and 

https://github.com/seqeralabs/nf-tower/blob/bf03b236ab43bd2b11b7e389e2c54408d266d8c2/tower-backend/src/main/groovy/io/seqera/tower/service/auth/AuthenticationByMailAuthToken.groovy

**Comment by clvadym** [comment]
@pditommaso **So how I see this flow:** 
When a user clicks on the login with GitHub, he is redirecting to the GitHub page where he can accept authentication. After that, he is going back on our site with query params: "code" and "state". Then we should send "code" to the back-end side and receive from it user's info (email, first name, last name, image, etc...). and if a user with this email exists - we should rewrite his data in the database but if he doesn't exist, then we should register him, generate token and return to the front-end side without email confirmation cause he has already accepted login with GitHub.

**Comment by pditommaso** [comment]
You may be right, even though I have the feeling that your approach is bypassing the auth mechanism implemented by micronaut.

**Comment by pditommaso** [comment]
Not merged.

**Pull request closed without merging**
