### PR TITLE
Add syntax highlighting to code snippets

### LINKED ISSUE #162: Add code syntax highlighting
A small but nice touch would be to use [highlightjs](https://highlightjs.org/) ([available on npm](https://www.npmjs.com/package/highlightjs)) to give syntax highlighting to code snippets. Main spots that spring to mind where this could be used (but I'm sure that there are other places too):

* The "Getting Started" welcome page
* The nextflow launch command
* The "Resolved configuration" section in Config

### PR DESCRIPTION
**Pull request by ewels**
Added [highlight.js](https://highlightjs.org/) via the [ngx-highlightjs](https://www.npmjs.com/package/ngx-highlightjs) npm package, to give nice syntax highlighting for code snippets.

Closes #162

image

---

image

### CODE REVIEW

**Comment by ewels** [comment]
NB: It would be really nice to have syntax highlighting for the task commands, here: https://github.com/seqeralabs/nf-tower/blob/821e4f5316680d6f89c18c13f2e6718668863b1a/tower-web/src/app/modules/main/component/tasks-table/tasks-table.component.ts#L258

However, because that's inserted as a string and not through a template, the highlighting doesn't work. I think that the way to sort this is to make a new angular component for the table row child content, and then dynamically render that. Then there is a proper template and everything can be a a bit more angular-ish (eg. use `ngFor` instead of ts for loops, templating etc). But I'm not sure that I have the energy to do this refactoring right now..

**Comment by ewels** [comment]
Merge conflicts fixed and updated with `master` again..

**Comment by pditommaso** [comment]
I've spotted a minor change always in the footer that I would like to keep as it was. 

If you noticed the footer was centred and was not touching the left/right margin: 

Screenshot 2019-12-02 at 17 29 35

Instead now is aligned to the window frame.  
Screenshot 2019-12-02 at 17 29 30

Any tip to rollback how it was? just adding some padding on the left and right?

**Comment by pditommaso** [comment]
Ok, spotted just using `container` instead of `container-fluid` should do the trick https://github.com/seqeralabs/nf-tower/blob/65effdfc84c8b8d932504627d183b7cfb12caa86/tower-web/src/app/modules/main/component/home/home.component.html#L30

**Comment by pditommaso** [comment]
AHHHHHHH CSS!!
Screenshot 2019-12-02 at 17 39 15

**Comment by pditommaso** [comment]
Crap, was posting in the wrong issue .. 🤦‍♂

**Comment by ewels** [comment]
No worries, can discuss here. How come you don't want it full width? I assumed that it was a bug that I fixed.. 😁 Everything else on that page is fluid and full width..?

**Comment by ewels** [comment]
@pditommaso - Are you guys still interested in this PR? Let me know if so and I can fix the merge conflicts / check it still works. Otherwise I might close it, as it's just going to get stale and get more and more out of date.

Phil

**Comment by pditommaso** [comment]
Hi Phil, thanks for this I think it's better to keep it simple.

**Comment by ewels** [comment]
Fair enough 😞

**Comment by ewels** [comment]
I will keep the branch around, just in case you get any more requests for syntax highlighting in the future 😉 (personally I find it makes a huge difference, but I know that I'm pretty far up the visual end of the visual-text spectrum)

**Pull request closed without merging**
